/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kolkoikrzyzyk;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author lewandowskikacper
 */


public class KolkoIKrzyzyk extends javax.swing.JFrame {

    public class Przyciski {

    public void off() {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
    }
}
    /**
     * Creates new form KolkoIKrzyzyk
     */
    String sign1 = "";
    String sign2 = "";
    int score1 = 0;
    int score2 = 0;
    int first = 1;
    Icon icon = new ImageIcon("");
    Icon icon2 = new ImageIcon("");
    Icon icon3 = new ImageIcon("/home/lewandowskikacper/Desktop/obrazy/nothing.jpg");
    ArrayList<Integer> list = new ArrayList<>(8);
    Przyciski p = new Przyciski();
    
    
    public KolkoIKrzyzyk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFName1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFName2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCB1 = new javax.swing.JComboBox<>();
        jCB2 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jBNewGame = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBNextGame = new javax.swing.JButton();
        jLName1 = new javax.swing.JLabel();
        jLName2 = new javax.swing.JLabel();
        jLPoints1 = new javax.swing.JLabel();
        jLPoints2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel1.setText("Nazwa Gracza 1");

        jTFName1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel2.setText("Nazwa Gracza 2");

        jTFName2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("sansserif", 3, 36)); // NOI18N
        jLabel3.setText("Kółko i krzyżyk");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel9.setText("Rodzaj symbolu");

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel10.setText("Rodzaj symbolu");

        jCB1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kółko", "Krzyżyk" }));

        jCB2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Krzyżyk", "Kółko" }));
        jCB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB2ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 51, 153));
        jButton11.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButton11.setText("Wyjdź");
        jButton11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setPreferredSize(new java.awt.Dimension(140, 70));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jBNewGame.setBackground(new java.awt.Color(0, 51, 153));
        jBNewGame.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jBNewGame.setText("Nowa sesja");
        jBNewGame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBNewGame.setPreferredSize(new java.awt.Dimension(140, 70));
        jBNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNewGameActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(0, 51, 153));
        jButton13.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButton13.setText("Jak grać?");
        jButton13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton13.setPreferredSize(new java.awt.Dimension(140, 70));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTFName1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFName2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addComponent(jBNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gracze", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 51, 0));

        jButton1.setBackground(new java.awt.Color(255, 128, 0));
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setPreferredSize(new java.awt.Dimension(135, 135));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 128, 0));
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setPreferredSize(new java.awt.Dimension(135, 135));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 128, 0));
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setPreferredSize(new java.awt.Dimension(135, 135));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 128, 0));
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setPreferredSize(new java.awt.Dimension(135, 135));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 128, 0));
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setPreferredSize(new java.awt.Dimension(135, 135));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 128, 0));
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.setPreferredSize(new java.awt.Dimension(135, 135));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 128, 0));
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.setPreferredSize(new java.awt.Dimension(135, 135));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 128, 0));
        jButton8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton8.setPreferredSize(new java.awt.Dimension(135, 135));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 128, 0));
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.setPreferredSize(new java.awt.Dimension(135, 135));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 26)); // NOI18N
        jLabel4.setText("Wygrał ");

        jBNextGame.setBackground(new java.awt.Color(255, 153, 153));
        jBNextGame.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jBNextGame.setText("Następna gra");
        jBNextGame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBNextGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNextGameActionPerformed(evt);
            }
        });

        jLName1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLName1.setText("Gracz 1");

        jLName2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLName2.setText("Gracz 2");

        jLPoints1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLPoints1.setText("0 ");

        jLPoints2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLPoints2.setText("0 ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLName1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLPoints1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLPoints2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBNextGame, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLPoints1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLPoints2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jBNextGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gra", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNextGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNextGameActionPerformed
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton1.setIcon(icon3);
        jButton2.setIcon(icon3);
        jButton3.setIcon(icon3);
        jButton4.setIcon(icon3);
        jButton5.setIcon(icon3);
        jButton6.setIcon(icon3);
        jButton7.setIcon(icon3);
        jButton8.setIcon(icon3);
        jButton9.setIcon(icon3);
        list.clear();
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        first = 1;

    }//GEN-LAST:event_jBNextGameActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String name1 = jTFName1.getText();
        String name2 = jTFName2.getText();
        first = first+1;
        if(first % 2 == 0){
            jButton9.setIcon(icon);
            jButton9.setEnabled(false);
            list.set(8,1);
        } else {
            jButton9.setIcon(icon2);
            jButton9.setEnabled(false);
            list.set(8,2);
        }

        int L1 = list.get(0);
        int L2 = list.get(1);
        int L3 = list.get(2);
        int L4 = list.get(3);
        int L5 = list.get(4);
        int L6 = list.get(5);
        int L7 = list.get(6);
        int L8 = list.get(7);
        int L9 = list.get(8);

        if(L1 == 1 && L2 == 1 && L3 ==1){

            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);

        } else if (L4 == 1 && L5 == 1 && L6 ==1){
            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
        } else if (L7 == 1 && L8 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 1 && L4 == 1 && L7 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L2 == 1 && L5 == 1 && L8 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 1 && L6 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if(L1 == 2 && L2 == 2 && L3 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L4 == 2 && L5 == 2 && L6 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L7 == 2 && L8 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 2 && L4 == 2 && L7 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L2 == 2 && L5 == 2 && L8 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 2 && L6 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 1 && L5 == 1 && L9 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 2 && L5 == 2 && L9 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 1 && L5 == 1 && L7 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 2 && L5 == 2 && L7 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String name1 = jTFName1.getText();
        String name2 = jTFName2.getText();
        first = first+1;
        if(first % 2 == 0){
            jButton8.setIcon(icon);
            jButton8.setEnabled(false);
            list.set(7,1);
        } else {
            jButton8.setIcon(icon2);
            jButton8.setEnabled(false);
            list.set(7,2);
        }

        int L1 = list.get(0);
        int L2 = list.get(1);
        int L3 = list.get(2);
        int L4 = list.get(3);
        int L5 = list.get(4);
        int L6 = list.get(5);
        int L7 = list.get(6);
        int L8 = list.get(7);
        int L9 = list.get(8);

        if(L1 == 1 && L2 == 1 && L3 ==1){

            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);

        } else if (L4 == 1 && L5 == 1 && L6 ==1){
            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
        } else if (L7 == 1 && L8 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 1 && L4 == 1 && L7 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L2 == 1 && L5 == 1 && L8 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 1 && L6 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if(L1 == 2 && L2 == 2 && L3 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L4 == 2 && L5 == 2 && L6 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L7 == 2 && L8 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 2 && L4 == 2 && L7 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L2 == 2 && L5 == 2 && L8 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 2 && L6 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 1 && L5 == 1 && L9 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 2 && L5 == 2 && L9 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 1 && L5 == 1 && L7 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 2 && L5 == 2 && L7 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String name1 = jTFName1.getText();
        String name2 = jTFName2.getText();
        first = first+1;
        if(first % 2 == 0){
            jButton7.setIcon(icon);
            jButton7.setEnabled(false);
            list.set(6,1);
        } else {
            jButton7.setIcon(icon2);
            jButton7.setEnabled(false);
            list.set(6,2);
        }

        int L1 = list.get(0);
        int L2 = list.get(1);
        int L3 = list.get(2);
        int L4 = list.get(3);
        int L5 = list.get(4);
        int L6 = list.get(5);
        int L7 = list.get(6);
        int L8 = list.get(7);
        int L9 = list.get(8);

        if(L1 == 1 && L2 == 1 && L3 ==1){

            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);

        } else if (L4 == 1 && L5 == 1 && L6 ==1){
            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
        } else if (L7 == 1 && L8 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 1 && L4 == 1 && L7 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L2 == 1 && L5 == 1 && L8 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 1 && L6 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if(L1 == 2 && L2 == 2 && L3 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L4 == 2 && L5 == 2 && L6 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L7 == 2 && L8 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 2 && L4 == 2 && L7 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L2 == 2 && L5 == 2 && L8 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 2 && L6 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 1 && L5 == 1 && L9 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 2 && L5 == 2 && L9 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 1 && L5 == 1 && L7 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 2 && L5 == 2 && L7 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String name1 = jTFName1.getText();
        String name2 = jTFName2.getText();
        first = first+1;
        if(first % 2 == 0){
            jButton6.setIcon(icon);
            jButton6.setEnabled(false);
            list.set(5,1);
        } else {
            jButton6.setIcon(icon2);
            jButton6.setEnabled(false);
            list.set(5,2);
        }

        int L1 = list.get(0);
        int L2 = list.get(1);
        int L3 = list.get(2);
        int L4 = list.get(3);
        int L5 = list.get(4);
        int L6 = list.get(5);
        int L7 = list.get(6);
        int L8 = list.get(7);
        int L9 = list.get(8);

        if(L1 == 1 && L2 == 1 && L3 ==1){

            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);

        } else if (L4 == 1 && L5 == 1 && L6 ==1){
            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
        } else if (L7 == 1 && L8 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 1 && L4 == 1 && L7 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L2 == 1 && L5 == 1 && L8 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 1 && L6 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if(L1 == 2 && L2 == 2 && L3 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L4 == 2 && L5 == 2 && L6 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L7 == 2 && L8 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 2 && L4 == 2 && L7 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L2 == 2 && L5 == 2 && L8 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 2 && L6 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 1 && L5 == 1 && L9 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 2 && L5 == 2 && L9 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 1 && L5 == 1 && L7 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 2 && L5 == 2 && L7 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String name1 = jTFName1.getText();
        String name2 = jTFName2.getText();
        first = first+1;
        if(first % 2 == 0){
            jButton5.setIcon(icon);
            jButton5.setEnabled(false);
            list.set(4,1);
        } else {
            jButton5.setIcon(icon2);
            jButton5.setEnabled(false);
            list.set(4,2);
        }

        int L1 = list.get(0);
        int L2 = list.get(1);
        int L3 = list.get(2);
        int L4 = list.get(3);
        int L5 = list.get(4);
        int L6 = list.get(5);
        int L7 = list.get(6);
        int L8 = list.get(7);
        int L9 = list.get(8);

        if(L1 == 1 && L2 == 1 && L3 ==1){

            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);

        } else if (L4 == 1 && L5 == 1 && L6 ==1){
            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
        } else if (L7 == 1 && L8 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 1 && L4 == 1 && L7 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L2 == 1 && L5 == 1 && L8 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 1 && L6 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if(L1 == 2 && L2 == 2 && L3 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L4 == 2 && L5 == 2 && L6 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L7 == 2 && L8 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 2 && L4 == 2 && L7 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L2 == 2 && L5 == 2 && L8 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 2 && L6 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 1 && L5 == 1 && L9 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 2 && L5 == 2 && L9 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 1 && L5 == 1 && L7 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 2 && L5 == 2 && L7 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name1 = jTFName1.getText();
        String name2 = jTFName2.getText();
        first = first+1;
        if(first % 2 == 0){
            jButton4.setIcon(icon);
            jButton4.setEnabled(false);
            list.set(3,1);
        } else {
            jButton4.setIcon(icon2);
            jButton4.setEnabled(false);
            list.set(3,2);
        }

        int L1 = list.get(0);
        int L2 = list.get(1);
        int L3 = list.get(2);
        int L4 = list.get(3);
        int L5 = list.get(4);
        int L6 = list.get(5);
        int L7 = list.get(6);
        int L8 = list.get(7);
        int L9 = list.get(8);

        if(L1 == 1 && L2 == 1 && L3 ==1){

            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);

        } else if (L4 == 1 && L5 == 1 && L6 ==1){
            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
        } else if (L7 == 1 && L8 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 1 && L4 == 1 && L7 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L2 == 1 && L5 == 1 && L8 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 1 && L6 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if(L1 == 2 && L2 == 2 && L3 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L4 == 2 && L5 == 2 && L6 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L7 == 2 && L8 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 2 && L4 == 2 && L7 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L2 == 2 && L5 == 2 && L8 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 2 && L6 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 1 && L5 == 1 && L9 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 2 && L5 == 2 && L9 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 1 && L5 == 1 && L7 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 2 && L5 == 2 && L7 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String name1 = jTFName1.getText();
        String name2 = jTFName2.getText();
        first = first+1;
        if(first % 2 == 0){
            jButton3.setIcon(icon);
            jButton3.setEnabled(false);
            list.set(2,1);
        } else {
            jButton3.setIcon(icon2);
            jButton3.setEnabled(false);
            list.set(2,2);
        }

        int L1 = list.get(0);
        int L2 = list.get(1);
        int L3 = list.get(2);
        int L4 = list.get(3);
        int L5 = list.get(4);
        int L6 = list.get(5);
        int L7 = list.get(6);
        int L8 = list.get(7);
        int L9 = list.get(8);

        if(L1 == 1 && L2 == 1 && L3 ==1){

            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);

        } else if (L4 == 1 && L5 == 1 && L6 ==1){
            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
        } else if (L7 == 1 && L8 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 1 && L4 == 1 && L7 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L2 == 1 && L5 == 1 && L8 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 1 && L6 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if(L1 == 2 && L2 == 2 && L3 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L4 == 2 && L5 == 2 && L6 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L7 == 2 && L8 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 2 && L4 == 2 && L7 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L2 == 2 && L5 == 2 && L8 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 2 && L6 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 1 && L5 == 1 && L9 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 2 && L5 == 2 && L9 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 1 && L5 == 1 && L7 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 2 && L5 == 2 && L7 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name1 = jTFName1.getText();
        String name2 = jTFName2.getText();

        first = first+1;
        if(first % 2 == 0){
            jButton2.setIcon(icon);
            jButton2.setEnabled(false);
            list.set(1,1);
        } else {
            jButton2.setIcon(icon2);
            jButton2.setEnabled(false);
            list.set(1,2);
        }

        int L1 = list.get(0);
        int L2 = list.get(1);
        int L3 = list.get(2);
        int L4 = list.get(3);
        int L5 = list.get(4);
        int L6 = list.get(5);
        int L7 = list.get(6);
        int L8 = list.get(7);
        int L9 = list.get(8);

        if(L1 == 1 && L2 == 1 && L3 ==1){
            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
        } else if (L4 == 1 && L5 == 1 && L6 ==1){
            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
        } else if (L7 == 1 && L8 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 1 && L4 == 1 && L7 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L2 == 1 && L5 == 1 && L8 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 1 && L6 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if(L1 == 2 && L2 == 2 && L3 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L4 == 2 && L5 == 2 && L6 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L7 == 2 && L8 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 2 && L4 == 2 && L7 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L2 == 2 && L5 == 2 && L8 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 2 && L6 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 1 && L5 == 1 && L9 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 2 && L5 == 2 && L9 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 1 && L5 == 1 && L7 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 2 && L5 == 2 && L7 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name1 = jTFName1.getText();
        String name2 = jTFName2.getText();
        first = first+1;
        if(first % 2 == 0){
            jButton1.setIcon(icon);
            jButton1.setEnabled(false);
            list.set(0,1);
        } else {
            jButton1.setIcon(icon2);
            jButton1.setEnabled(false);
            list.set(0,2);
        }

        int L1 = list.get(0);
        int L2 = list.get(1);
        int L3 = list.get(2);
        int L4 = list.get(3);
        int L5 = list.get(4);
        int L6 = list.get(5);
        int L7 = list.get(6);
        int L8 = list.get(7);
        int L9 = list.get(8);

        if(L1 == 1 && L2 == 1 && L3 ==1){

            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);

        } else if (L4 == 1 && L5 == 1 && L6 ==1){
            score1 = score1 + 1;
            jLPoints1.setText(Integer.toString(score1));
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
        } else if (L7 == 1 && L8 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 1 && L4 == 1 && L7 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L2 == 1 && L5 == 1 && L8 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 1 && L6 == 1 && L9 ==1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if(L1 == 2 && L2 == 2 && L3 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L4 == 2 && L5 == 2 && L6 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L7 == 2 && L8 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 2 && L4 == 2 && L7 ==2){
            score2 = score2 + 1;
            z.zapisz(name1, sign1, name2, sign2, name2);
            p.off();
            jLPoints2.setText(Integer.toString(score2));
        } else if (L2 == 2 && L5 == 2 && L8 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 2 && L6 == 2 && L9 ==2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L1 == 1 && L5 == 1 && L9 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L1 == 2 && L5 == 2 && L9 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        } else if (L3 == 1 && L5 == 1 && L7 == 1){
            score1 = score1 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name1);
            jLPoints1.setText(Integer.toString(score1));
        } else if (L3 == 2 && L5 == 2 && L7 == 2){
            score2 = score2 + 1;
            p.off();
            z.zapisz(name1, sign1, name2, sign2, name2);
            jLPoints2.setText(Integer.toString(score2));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        JOptionPane.showMessageDialog(this, "Kto ułoży 3 te same znaki w pionie, poziomie lub po skosie, ten wygrywa.");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jBNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNewGameActionPerformed
        String name1 = jTFName1.getText();
        String name2 = jTFName2.getText();
        jLName1.setText(name1);
        jLName2.setText(name2);
        sign1 = jCB1.getSelectedItem().toString();
        sign2 = jCB2.getSelectedItem().toString();
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton1.setIcon(icon3);
        jButton2.setIcon(icon3);
        jButton3.setIcon(icon3);
        jButton4.setIcon(icon3);
        jButton5.setIcon(icon3);
        jButton6.setIcon(icon3);
        jButton7.setIcon(icon3);
        jButton8.setIcon(icon3);
        jButton9.setIcon(icon3);
        if (sign1.equals("Kółko")){
            icon = new ImageIcon("/home/lewandowskikacper/Desktop/obrazy/o.jpg");
        }
        if (sign2.equals("Kółko")){
            icon2 = new ImageIcon("/home/lewandowskikacper/Desktop/obrazy/o.jpg");
        }
        if (sign1.equals("Krzyżyk")){
            icon = new ImageIcon("/home/lewandowskikacper/Desktop/obrazy/x.jpg");
        }
        if (sign2.equals("Krzyżyk")){
            icon2 = new ImageIcon("/home/lewandowskikacper/Desktop/obrazy/x.jpg");
        }
        if (sign1.equals(sign2)){
            jLabel5.setText("Wybraliście tan sam znak!!!");
        } else {
            jLabel5.setText("");
        }
        list.clear();
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        list.add(9);
        score1 = 0;
        score2 = 0;
        first = 1;

    }//GEN-LAST:event_jBNewGameActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jCB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KolkoIKrzyzyk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KolkoIKrzyzyk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KolkoIKrzyzyk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KolkoIKrzyzyk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KolkoIKrzyzyk().setVisible(true);
            }
        });
    }
    Zapisz z = new Zapisz();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBNewGame;
    private javax.swing.JButton jBNextGame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jCB1;
    private javax.swing.JComboBox<String> jCB2;
    private javax.swing.JLabel jLName1;
    private javax.swing.JLabel jLName2;
    private javax.swing.JLabel jLPoints1;
    private javax.swing.JLabel jLPoints2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFName1;
    private javax.swing.JTextField jTFName2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
