/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.wlasnyprojektaplikacji;

import java.io.IOException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.util.logging.*;
import java.util.Scanner;
import java.awt.Font;

/**
 *
 * @author kacpe
 */
public class WlasnyProjektAplikacji extends javax.swing.JFrame {

    /**
     * Creates new form WlasnyProjektAplikacji
     */
    public WlasnyProjektAplikacji() {
        initComponents();
        f = new File("wyniki_bmr.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRBMan = new javax.swing.JRadioButton();
        jRBWoman = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTFWeight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFHeight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFPAL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLBMR = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAHistory = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jBCalculate = new javax.swing.JButton();
        jBWrite = new javax.swing.JButton();
        jBRead = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMPlik = new javax.swing.JMenu();
        jMIZapisz = new javax.swing.JMenuItem();
        jMIWczytaj = new javax.swing.JMenuItem();
        jMIZamknij = new javax.swing.JMenuItem();
        jMEdycja = new javax.swing.JMenu();
        jMCzcionka = new javax.swing.JMenu();
        jMFreeMono = new javax.swing.JMenuItem();
        jMZ003 = new javax.swing.JMenuItem();
        jMSarai = new javax.swing.JMenuItem();
        jMITlo = new javax.swing.JMenuItem();
        jMOProgramie = new javax.swing.JMenu();
        jMIProgram = new javax.swing.JMenuItem();
        jMIHelp = new javax.swing.JMenuItem();

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator zapotrzebowania kalorycznego");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Podaj płeć:");

        jRBMan.setBackground(new java.awt.Color(51, 204, 255));
        buttonGroup1.add(jRBMan);
        jRBMan.setText("Mężczyzna");
        jRBMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBManActionPerformed(evt);
            }
        });

        jRBWoman.setBackground(new java.awt.Color(51, 204, 255));
        buttonGroup1.add(jRBWoman);
        jRBWoman.setText("Kobieta");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Podaj wagę:");

        jTFWeight.setPreferredSize(new java.awt.Dimension(80, 25));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Podaj wiek:");

        jTFAge.setPreferredSize(new java.awt.Dimension(80, 25));
        jTFAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAgeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Podaj wzrost(cm):");

        jTFHeight.setPreferredSize(new java.awt.Dimension(80, 25));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Podaj PAL:");

        jTFPAL.setPreferredSize(new java.awt.Dimension(80, 25));
        jTFPAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPALActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Twoje BMR wynosi:");

        jLBMR.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLBMR.setText("XXX");
        jLBMR.setToolTipText("");
        jLBMR.setPreferredSize(new java.awt.Dimension(80, 25));

        jTAHistory.setColumns(20);
        jTAHistory.setRows(5);
        jScrollPane1.setViewportView(jTAHistory);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Historia wyników:");

        jBCalculate.setText("OBLICZ");
        jBCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalculateActionPerformed(evt);
            }
        });

        jBWrite.setText("ZAPISZ");
        jBWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBWriteActionPerformed(evt);
            }
        });

        jBRead.setText("WCZYTAJ");
        jBRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFPAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBWoman)
                                    .addComponent(jRBMan)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBCalculate)
                                .addGap(56, 56, 56)
                                .addComponent(jBWrite))
                            .addComponent(jLBMR, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(jBRead))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRBMan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBWoman)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTFWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTFHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTFPAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLBMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBCalculate)
                                    .addComponent(jBWrite)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jBRead))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1))))
                    .addComponent(jLabel8))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 204));
        jMenuBar1.setBorder(null);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(157, 25));

        jMPlik.setText("Plik");

        jMIZapisz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIZapisz.setText("Zapisz");
        jMIZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIZapiszActionPerformed(evt);
            }
        });
        jMPlik.add(jMIZapisz);

        jMIWczytaj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIWczytaj.setText("Wczytaj");
        jMPlik.add(jMIWczytaj);

        jMIZamknij.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIZamknij.setText("Zamknij program");
        jMIZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIZamknijActionPerformed(evt);
            }
        });
        jMPlik.add(jMIZamknij);

        jMenuBar1.add(jMPlik);

        jMEdycja.setText("Edycja");

        jMCzcionka.setText("Zmień czcionkę");

        jMFreeMono.setText("FreeMono");
        jMFreeMono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFreeMonoActionPerformed(evt);
            }
        });
        jMCzcionka.add(jMFreeMono);

        jMZ003.setText("Z003");
        jMCzcionka.add(jMZ003);

        jMSarai.setText("Sarai");
        jMCzcionka.add(jMSarai);

        jMEdycja.add(jMCzcionka);

        jMITlo.setText("Zmień tło");
        jMEdycja.add(jMITlo);

        jMenuBar1.add(jMEdycja);

        jMOProgramie.setText("O programie");

        jMIProgram.setText("O programie");
        jMOProgramie.add(jMIProgram);

        jMIHelp.setText("Help");
        jMOProgramie.add(jMIHelp);

        jMenuBar1.add(jMOProgramie);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIZapiszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIZapiszActionPerformed

    private void jRBManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBManActionPerformed

    private void jTFAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAgeActionPerformed

    private void jTFPALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPALActionPerformed

    private void jBCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalculateActionPerformed
        String weight = jTFWeight.getText();
        String age = jTFAge.getText();
        String height = jTFHeight.getText();
        String pal = jTFPAL.getText();
        int a = Integer.parseInt(weight);
        int b = Integer.parseInt(age);
        int c = Integer.parseInt(height);
        double d = Double.parseDouble(pal);
        if (jRBMan.isSelected()){
            jLBMR.setText(66+(13.7*a)+(5*c)-(6.8*b)*d+"kcal");
        } else if (jRBWoman.isSelected()){
            jLBMR.setText(655+(9.6*a)+(1.8*c)-(4.7*b)*d+"kcal");
        }
        
    }//GEN-LAST:event_jBCalculateActionPerformed

    private void jBWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBWriteActionPerformed
        String gender = "Mężczyzna";
        if (jRBWoman.isSelected()){
            gender = "Kobieta";
        }
        String weight = jTFWeight.getText();
        String age = jTFAge.getText();
        String height = jTFHeight.getText();
        String pal = jTFPAL.getText();
        String bmr = jLBMR.getText();
        try{
            FileWriter fw = new FileWriter(f, true);
            fw.write("Twój wynik:"+"\n");
            fw.write(weight+" cm"+"\n");
            fw.write(age+"\n");
            fw.write(height+" kg"+"\n");
            fw.write(pal+"\n");
            fw.write(bmr+"\n");
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(WlasnyProjektAplikacji.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBWriteActionPerformed

    private void jBReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReadActionPerformed
        try{
            Scanner sc = new Scanner(f);
            String data = "";
            while(sc.hasNext()){
                data += sc.nextLine()+System.lineSeparator();
            }
            jTAHistory.setText(data);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(WlasnyProjektAplikacji.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBReadActionPerformed

    private void jMIZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMIZamknijActionPerformed

    private void jMFreeMonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFreeMonoActionPerformed
        Font a = new Font("sarai", Font.BOLD, 14);
        Font b = new Font("sarai", Font.BOLD, 18);
        Font c = new Font("sarai", Font.BOLD, 24);
        Font d = new Font("sarai", Font.BOLD, 11);
        jLabel1.setFont(a);
        jLabel2.setFont(a);
        jLabel3.setFont(a);
        jLabel5.setFont(a);
        jLabel6.setFont(a);
        jLabel7.setFont(b);
        jLabel9.setFont(c);
        jLBMR.setFont(c);
        jRBMan.setFont(d);
        jRBWoman.setFont(d);
        jTFWeight.setFont(d);
    }//GEN-LAST:event_jMFreeMonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjektAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjektAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjektAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjektAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WlasnyProjektAplikacji().setVisible(true);
            }
        });
    }
    File f;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCalculate;
    private javax.swing.JButton jBRead;
    private javax.swing.JButton jBWrite;
    private javax.swing.JLabel jLBMR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMCzcionka;
    private javax.swing.JMenu jMEdycja;
    private javax.swing.JMenuItem jMFreeMono;
    private javax.swing.JMenuItem jMIHelp;
    private javax.swing.JMenuItem jMIProgram;
    private javax.swing.JMenuItem jMITlo;
    private javax.swing.JMenuItem jMIWczytaj;
    private javax.swing.JMenuItem jMIZamknij;
    private javax.swing.JMenuItem jMIZapisz;
    private javax.swing.JMenu jMOProgramie;
    private javax.swing.JMenu jMPlik;
    private javax.swing.JMenuItem jMSarai;
    private javax.swing.JMenuItem jMZ003;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBMan;
    private javax.swing.JRadioButton jRBWoman;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAHistory;
    private javax.swing.JTextField jTFAge;
    private javax.swing.JTextField jTFHeight;
    private javax.swing.JTextField jTFPAL;
    private javax.swing.JTextField jTFWeight;
    // End of variables declaration//GEN-END:variables
}
