/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.wlasnyprojektaplikacji;

/**
 *
 * @author kacpe
 */
public class WlasnyProjektAplikacji extends javax.swing.JFrame {

    /**
     * Creates new form WlasnyProjektAplikacji
     */
    public WlasnyProjektAplikacji() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMPlik = new javax.swing.JMenu();
        jMIZapisz = new javax.swing.JMenuItem();
        jMIWczytaj = new javax.swing.JMenuItem();
        jMIZamknij = new javax.swing.JMenuItem();
        jMEdycja = new javax.swing.JMenu();
        jMICzcionka = new javax.swing.JMenuItem();
        jMITlo = new javax.swing.JMenuItem();
        jMOProgramie = new javax.swing.JMenu();
        jMIProgram = new javax.swing.JMenuItem();
        jMIHelp = new javax.swing.JMenuItem();

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator zapotrzebowania kalorycznego");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 153));
        jMenuBar1.setBorder(null);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(157, 25));

        jMPlik.setText("Plik");

        jMIZapisz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIZapisz.setText("Zapisz");
        jMIZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIZapiszActionPerformed(evt);
            }
        });
        jMPlik.add(jMIZapisz);

        jMIWczytaj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIWczytaj.setText("Wczytaj");
        jMPlik.add(jMIWczytaj);

        jMIZamknij.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIZamknij.setText("Zamknij program");
        jMPlik.add(jMIZamknij);

        jMenuBar1.add(jMPlik);

        jMEdycja.setText("Edycja");

        jMICzcionka.setText("Zmień czcionkę");
        jMEdycja.add(jMICzcionka);

        jMITlo.setText("Zmień tło");
        jMEdycja.add(jMITlo);

        jMenuBar1.add(jMEdycja);

        jMOProgramie.setText("O programie");

        jMIProgram.setText("O programie");
        jMOProgramie.add(jMIProgram);

        jMIHelp.setText("Help");
        jMOProgramie.add(jMIHelp);

        jMenuBar1.add(jMOProgramie);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIZapiszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIZapiszActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjektAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjektAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjektAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjektAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WlasnyProjektAplikacji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMEdycja;
    private javax.swing.JMenuItem jMICzcionka;
    private javax.swing.JMenuItem jMIHelp;
    private javax.swing.JMenuItem jMIProgram;
    private javax.swing.JMenuItem jMITlo;
    private javax.swing.JMenuItem jMIWczytaj;
    private javax.swing.JMenuItem jMIZamknij;
    private javax.swing.JMenuItem jMIZapisz;
    private javax.swing.JMenu jMOProgramie;
    private javax.swing.JMenu jMPlik;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
