/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.delta;
import java.util.Scanner;
/**
 *
 * @author kacpe
 */
public class Delta extends javax.swing.JFrame {

    /**
     * Creates new form Delta
     */
    public Delta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLA = new javax.swing.JLabel();
        jLB = new javax.swing.JLabel();
        jLC = new javax.swing.JLabel();
        jLD = new javax.swing.JLabel();
        jL0 = new javax.swing.JLabel();
        jLW = new javax.swing.JLabel();
        jLZW = new javax.swing.JLabel();
        jLAA = new javax.swing.JLabel();
        jLBA = new javax.swing.JLabel();
        jLCA = new javax.swing.JLabel();
        jLDA = new javax.swing.JLabel();
        jL0A1 = new javax.swing.JLabel();
        jL0A2 = new javax.swing.JLabel();
        jLWA1 = new javax.swing.JLabel();
        jLWA2 = new javax.swing.JLabel();
        jLZWA = new javax.swing.JLabel();
        jBS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DELTA");
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLA.setForeground(new java.awt.Color(153, 102, 255));
        jLA.setText("Podaj a:");

        jLB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLB.setForeground(new java.awt.Color(153, 102, 255));
        jLB.setText("Podaj b:");

        jLC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLC.setForeground(new java.awt.Color(153, 102, 255));
        jLC.setText("Podaj c:");

        jLD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLD.setForeground(new java.awt.Color(153, 102, 255));
        jLD.setText("Delta:");

        jL0.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jL0.setForeground(new java.awt.Color(153, 102, 255));
        jL0.setText("Miejsca zerowe:");

        jLW.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLW.setForeground(new java.awt.Color(153, 102, 255));
        jLW.setText("Współrzędne wierzchołka:");

        jLZW.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLZW.setForeground(new java.awt.Color(153, 102, 255));
        jLZW.setText("Zbiór wartości:");

        jLAA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLAA.setForeground(new java.awt.Color(153, 102, 255));
        jLAA.setText("???");

        jLBA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLBA.setForeground(new java.awt.Color(153, 102, 255));
        jLBA.setText("???");

        jLCA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLCA.setForeground(new java.awt.Color(153, 102, 255));
        jLCA.setText("???");

        jLDA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLDA.setForeground(new java.awt.Color(153, 102, 255));
        jLDA.setText("???");

        jL0A1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL0A1.setForeground(new java.awt.Color(153, 102, 255));
        jL0A1.setText("???");

        jL0A2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL0A2.setForeground(new java.awt.Color(153, 102, 255));
        jL0A2.setText("???");

        jLWA1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLWA1.setForeground(new java.awt.Color(153, 102, 255));
        jLWA1.setText("???");

        jLWA2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLWA2.setForeground(new java.awt.Color(153, 102, 255));
        jLWA2.setText("???");

        jLZWA.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLZWA.setForeground(new java.awt.Color(153, 102, 255));
        jLZWA.setText("???");
        jLZWA.setToolTipText("");

        jBS.setText("Start");
        jBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLC)
                        .addGap(18, 18, 18)
                        .addComponent(jLCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLB)
                        .addGap(18, 18, 18)
                        .addComponent(jLBA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLA)
                        .addGap(18, 18, 18)
                        .addComponent(jLAA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jL0)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL0A2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL0A1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLD)
                        .addGap(18, 18, 18)
                        .addComponent(jLDA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLZW)
                        .addGap(18, 18, 18)
                        .addComponent(jLZWA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLW)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLWA1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jLWA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLA)
                    .addComponent(jLAA))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLB)
                    .addComponent(jLBA))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLC)
                    .addComponent(jLCA))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLD)
                    .addComponent(jLDA))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL0)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jL0A1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL0A2)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLW)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLZW)
                            .addComponent(jLZWA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLWA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLWA2)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSActionPerformed
        Scanner sc = new Scanner(System.in);
        System.out.println("Podaj a");
        double a = sc.nextDouble();
        System.out.println("Podaj b");
        double b = sc.nextDouble();
        System.out.println("Podaj c");
        double c = sc.nextDouble();
        double del = b*b-4*a*c;;
        double x1 = (-b-Math.sqrt(del))/2*a;
        double x2 = (-b+Math.sqrt(del))/2*a;
        double p = -b/2*a;
        double q = del/4*a;
        
        jLAA.setText(String.valueOf(a));
        jLBA.setText(String.valueOf(b));
        jLCA.setText(String.valueOf(c));
        jLDA.setText(String.valueOf(del));
        if (del<0){
            jL0A1.setText("Brak miejsc zerowych");
            jL0A2.setText("Brak miejsc zerowych");
        } else {
            jL0A1.setText(String.valueOf(x1));
            jL0A2.setText(String.valueOf(x2)); 
        }
        jLWA1.setText(String.valueOf(p));
        jLWA2.setText(String.valueOf(q));
        if (a>=0){
            jLZWA.setText("x∈"+"(-∞;"+x1+") ∪ ("+x2+"; ∞");
        } else {
            jLZWA.setText("x∈<"+x1+";"+x2+">");
        }
    }//GEN-LAST:event_jBSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBS;
    private javax.swing.JLabel jL0;
    private javax.swing.JLabel jL0A1;
    private javax.swing.JLabel jL0A2;
    private javax.swing.JLabel jLA;
    private javax.swing.JLabel jLAA;
    private javax.swing.JLabel jLB;
    private javax.swing.JLabel jLBA;
    private javax.swing.JLabel jLC;
    private javax.swing.JLabel jLCA;
    private javax.swing.JLabel jLD;
    private javax.swing.JLabel jLDA;
    private javax.swing.JLabel jLW;
    private javax.swing.JLabel jLWA1;
    private javax.swing.JLabel jLWA2;
    private javax.swing.JLabel jLZW;
    private javax.swing.JLabel jLZWA;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
